Translate Searches for Numbers correctly
samply/lens-angular pull request #21
Opened 2023-07-25 15:59 UTC by torbrenner

2023-07-26 07:52 UTC, patrick-skowronek requested changes
The generated query does not work. Also I think the inputs in the HTML are in the wrong order.

2023-07-26 07:52 UTC, patrick-skowronek commented on core/cql/src/cql-translator.service.ts
> +    ["conditionRangeAge", "exists [Condition] C\nwhere AgeInYearsAt(FHIRHelpers.ToDateTime(C.onset)) >= {{D1}} and {{D2}}"],
This does generate a CQL query that is not working. I guess it is missing a operator before the second placeholder.

2023-07-26 08:00 UTC, alexanderkiel commented on core/cql/src/cql-translator.service.ts
> +    ["conditionRangeAge", "exists [Condition] C\nwhere AgeInYearsAt(FHIRHelpers.ToDateTime(C.onset)) >= {{D1}} and {{D2}}"],
Yes `x >= y and z` doesn't work. What was the problem with `between`?

2023-07-27 09:37 UTC, torbrenner commented on core/cql/src/cql-translator.service.ts
> +    ["conditionRangeAge", "exists [Condition] C\nwhere AgeInYearsAt(FHIRHelpers.ToDateTime(C.onset)) >= {{D1}} and {{D2}}"],
The templating didn't correctly replace either {C1} or {C2}. Strange that my local blaze instance executed the queries with `x >= 0`. Then I will try to make the templating work properly.

2023-08-17 13:29 UTC, torbrenner commented on core/cql/src/cql-translator.service.ts
> +    ["conditionRangeAge", "exists [Condition] C\nwhere AgeInYearsAt(FHIRHelpers.ToDateTime(C.onset)) >= {{D1}} and {{D2}}"],
Sorry, took me longer to look again at that issue. The `x >= y  and z` stuff was actually just me doing a false commit. I had in my editor `x between y and z` but not staged for a commit.
It should now be corrected

2023-08-17 13:53 UTC, patrickskowronekdkfz approved these changes
The query is now correct. However, the displayed data is very confusing with such a query. This should be discussed.

2023-08-22 07:57 UTC, merged