Ignore Responses that state claimed Requests
samply/lens-angular pull request #25
Opened 2023-09-20 07:17 UTC by torbrenner

Before, a failed request would crash the result parsing in lens due to the body of claimed being empty.

2023-09-20 07:29 UTC, Threated approved these changes

2023-09-20 11:49 UTC, Threated requested changes

2023-09-20 11:49 UTC, Threated commented on core/cql/src/beam.ts
> +          i = (response.body) ? finalizedResponses.length : i;
```suggestion
          i = response.body.length;
```
We checked that we have a body here already right?

2023-09-20 11:49 UTC, Threated commented on core/cql/src/beam.ts
> +        if (response.body != undefined) {
```suggestion
        if (response.body !== undefined) {
```

2023-09-20 11:49 UTC, Threated commented on core/cql/src/beam.ts
> +          if (this.currentTask != undefined && receivedTask.indexOf(this.currentTask.id) != -1) {
```suggestion
          if (this.currentTask !== undefined && receivedTask.indexOf(this.currentTask.id) !== -1) {
```

2023-09-20 11:49 UTC, Threated commented on core/cql/src/beam.ts
> +        } else if (result.status == "claimed") {
```suggestion
        } else if (result.status === "claimed") {
```
I see the above compares also use `==` as well but I think that is bad practice although I guess it does not matter for string compares like this at least.

2023-09-21 06:05 UTC, torbrenner commented on core/cql/src/beam.ts
> +          i = (response.body) ? finalizedResponses.length : i;
We can't take the response.body.length here, because that will result in lens thinking the claimed response is the final one and it wouldn't request beam any longer for new results, therefore we need the filtered version 'finalizedResponses'.
I commited a correction for the unnecessary check if response.body is defined.

2023-09-21 06:15 UTC, Threated approved these changes

2023-09-21 06:29 UTC, patrickskowronekdkfz approved these changes

2023-09-21 06:47 UTC, merged